# Generated by Django 3.1.2 on 2020-11-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Suggestions',
        ),
    ]
